# Generated by Django 3.2.4 on 2021-06-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_auto_20210606_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
